### Get All Categories
GET {{host}}/public/categories?pageNumber=2&sortBy=categoryId&sortOrder=desc

### Get A Category
@categoryId2 = 1
GET {{host}}/public/categories/{{categoryId2}}

##**********************************************************************
### Add A Category
POST {{host}}/admin/categories
Content-Type: application/json

{
  "categoryName": "Men's Fashion"
}

### Update A Category
@categoryId = 1
PUT {{host}}/admin/categories/{{categoryId}}
Content-Type: application/json

{
  "name": "Education and Industrial Training",
  "categoryId": 2
}

### Delete A Category
@categoryId3 = 1
DELETE {{host}}/admin/categories/{{categoryId3}}

## ******************* PRODUCT OPERATIONS ******************************************
##**********************************************************************************
### Add A Product
POST {{host}}/admin/category/2/product
Content-Type: application/json

{
  "productName": "Cotton Shirt",
  "description": "A beautiful piece of machinery...",
  "quantity": 10,
  "price": 3500.00,
  "discount": 25.00
}

### Get A Product
@fetchedProductId= 1
GET {{host}}/public/products/{fetchedProductId}

### Get All Products
GET {{host}}/public/products?pageNumber=0&pageSize=10&sortBy=productId&sortOrder=asc

### Get Products By Category
GET {{host}}/public/category/1/products

### Get Products By Keyword
GET {{host}}/public/products/keyword/custom

### Update A Product
@productId = 1
PUT {{host}}/admin/products/{{productId}}
Content-Type: application/json

{
  "productName": "Custom Legal Blocks",
  "description": "Comfy and durable casual footwear",
  "image": "default.png",
  "quantity": 20,
  "price": 1000.0,
  "discount": 50.0
}


### Delete A Product
@deletedProductId = 1
DELETE {{host}}/admin/products/{{deletedProductId}}