### Get All Categories
GET {{host}}/public/categories?pageNumber=2&sortBy=categoryId&sortOrder=desc

### Get A Category
@categoryId2 = 1
GET {{host}}/public/categories/{{categoryId2}}

##**********************************************************************
### Add A Category
POST {{host}}/admin/categories
Content-Type: application/json

{
  "name": "Advertising and Marketing"
}

### Update A Category
@categoryId = 1
PUT {{host}}/admin/categories/{{categoryId}}
Content-Type: application/json

{
  "name": "Education and Industrial Training"
}

### Delete A Category
@categoryId3 = 1
DELETE {{host}}/admin/categories/{{categoryId3}}

### Echo
GET {{host}}/echo?message=Hi

