spring.application.name=sb-ecom

spring.app.jwtSecret=mySecretKey123912738aopsgjnspkmndfsopkvajoirjg94gf2opfng2moknm
spring.app.jwtExpirationMs=3000000
spring.app.jwtCookieName=springBootEcom

#spring.h2.console.enabled=true
#spring.datasource.url=jdbc:h2:mem:test

#Postgres Configurations
spring.datasource.url=jdbc:postgresql://localhost:5432/sb_ecom
spring.datasource.username=postgres
spring.datasource.password=andy_123
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

project.image= images/

spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=update


#STRIPE KEY
stripe.secret.key=STRIPE_SECRET_KEY




